import os
import random
import re
from datetime import datetime

def get_unique_content(kw):
    """
    This replaces the OpenAI call. It builds unique content blocks 
    by shuffling data and injecting keywords.
    """
    # Core components to mix and match
    openers = [
        f"The evolution of {kw} has reached a turning point in 2026.",
        f"Understanding the impact of {kw} is essential for modern scaling.",
        f"As we look at the latest trends, {kw} stands out as a primary driver.",
        f"The technical landscape surrounding {kw} is shifting rapidly."
    ]
    
    technical_bullets = [
        f"Integrating high-fidelity ElevenLabs voice models into {kw} workflows.",
        f"Optimizing latency for real-time {kw} deployments.",
        f"Leveraging neural synthesis to enhance {kw} user engagement.",
        f"Cross-platform compatibility for all {kw} digital assets."
    ]
    
    closers = [
        f"Stay tuned for more updates on our {kw} research.",
        f"Explore how our Vulture Protocol is redefining {kw} at scale.",
        f"For further details on {kw}, check our daily technical briefings."
    ]

    # Descramble Logic
    random.shuffle(technical_bullets)
    
    html_output = f"""
    <p>{random.choice(openers)}</p>
    <ul>
        <li>{technical_bullets[0]}</li>
        <li>{technical_bullets[1]}</li>
        <li>{technical_bullets[2]}</li>
    </ul>
    <p>{random.choice(closers)}</p>
    """
    return html_output

def main():
    target_dir = 'pages'
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)

    # Load your keywords
    keywords_file = 'keywords.txt'
    if os.path.exists(keywords_file):
        with open(keywords_file, 'r') as f:
            keywords = [line.strip() for line in f if line.strip()]
    else:
        keywords = ["AI Voice Automation", "Neural Synthesis"]

    for kw in keywords:
        content = get_unique_content(kw)
        safe_name = re.sub(r'[^a-zA-Z0-9\s-]', '', kw.lower()).strip().replace(' ', '-')
        
        # Build the final HTML file
        with open(f"{target_dir}/{safe_name}.html", 'w') as f:
            f.write(f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{kw} | ElevenLabs 2026 Update</title>
    <style>body{{font-family:sans-serif;max-width:800px;margin:40px auto;line-height:1.6;padding:0 20px;}}</style>
</head>
<body>
    <h1>{kw}</h1>
    <div class="content">{content}</div>
    <hr>
    <p><small>Generated by Vulture Final Protocol - {datetime.now().strftime('%Y-%m-%d')}</small></p>
</body>
</html>""")

    print(f"✅ Successfully vultured {len(keywords)} pages without API costs.")

if __name__ == "__main__":
    main()
