- name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Vulture-Bot"
          # 'git add .' is safer because it catches the html, mp3, and the updated keywords list
          git add .
          # This line prevents the error if there happens to be nothing new to save
          git commit -m "Vulture Daily Update: $(date)" || echo "No changes to commit"
          git push
